# Site settings
title: Montalvo Miguelo
email: me@montalvomiguelo.com
description: Independent front-end developer and musician from México. I work for small businesses, start-ups, individuals, and fellow web and design agencies.
baseurl: "/montalvomiguelo" # the subpath of your site, e.g. /blog/
url: "http://montalvomiguelo.com" # the base hostname & protocol for your site
twitter_username: montalvomiguelo
github_username:  montalvomiguelo

# Build settings
markdown: kramdown
permalink: pretty
