# Site settings
title: Montalvo Miguelo
email: me@montalvomiguelo.com
tagline: Web developer and musician
description: Montalvo Miguelo is a full stack web developer in Mexico, building things for the internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://montalvomiguelo.com" # the base hostname & protocol for your site
twitter_username: montalvomiguelo
github_username:  montalvomiguelo

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Montalvo Miguelo
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Collections
collections:
  - projects

disqus:
  shortname: montalvomiguelo

google_analytics: UA-70263908-1
