# Site settings
title: Miguel Montalvo
email: me@montalvomiguelo.com
description: >
  <p>I am a software engineer at <a href="https://barrelny.com">Barrel</a>, a creative and digital marketing agency based in NY and LA.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://montalvomiguelo.com" # the base hostname & protocol for your site
twitter_username: montalvomiguelo
github_username:  montalvomiguelo

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Montalvo Miguelo
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Collections
collections:
  - projects

lang: es
