# Site settings
title: Montalvo Miguelo
email: me@montalvomiguelo.com
description: Desarrollador front-end y músico independiente. Colaboro con pequeñas y medianas empresas, start-ups, y agencias de diseño y desarollo web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://montalvomiguelo.com" # the base hostname & protocol for your site
twitter_username: montalvomiguelo
github_username:  montalvomiguelo

# Build settings
markdown: kramdown
permalink: pretty
