# Site settings
title: Montalvo Miguelo
email: me@montalvomiguelo.com
description: Independent front-end developer and musician from México. I work for small businesses, start-ups, individuals, and web/design agencies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://montalvomiguelo.com" # the base hostname & protocol for your site
twitter_username: montalvomiguelo
github_username:  montalvomiguelo

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed

# Front Matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Montalvo Miguelo
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "pages"
